# Generated by Django 6.0 on 2026-02-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0003_product_alter_profile_is_phone_verified_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quality',
            new_name='quatity',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_email_verifield',
            new_name='is_email_verified',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updates_At',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
