# Generated by Django 6.0 on 2026-02-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0004_rename_quality_orderitem_quatity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
