# Generated by Django 6.0 on 2026-02-03 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0005_rename_create_at_profile_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='unit_price',
        ),
    ]
