# Generated by Django 6.0.1 on 2026-02-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signuplogin', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
