# Generated by Django 6.0.1 on 2026-02-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signuplogin', '0005_product_average_rating_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
    ]
